name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag yosoy-local:$(date +%s)
